### ISSUE TITLE
HONKAI:STARRAIL

### ISSUE THREAD

**Issue by rkdrlgh22** [joeloewi7178/Croissant#200]
can i add starrail?
REALSE TODAY 23.04.26
I'd really appreciate it if you could add it. 
thank you

**Comment by joeloewi7178** [comment]
Hi, thank you for opening issue.
It maybe take some time because I'm currently working on fixing some errors found in candidate version.
I will try to publish new version until **end of this week**.

Thanks again, and feel free to open another issue.

**Comment by joeloewi7178** [comment]
Closing issue. 
New version released with version name 1.2.0. 
Please check play store.
