### ISSUE TITLE
ZZZ SUPPORT

### ISSUE THREAD

**Issue by rkdrlgh22** [joeloewi7178/Croissant#470]
can i add Z.Z.Z ? 
TOday realase 24.07.04
plz support Z.Z.Z
 thank you <3

**Comment by joeloewi7178** [comment]
Hi
I'm currently working on it, and new version will be released this week.

**Comment by rkdrlgh22** [comment]
Always Thank you <3 im waiting

**Comment by joeloewi7178** [comment]
Closing issue.
Version 1.3.2, which contains zzz check-in feature, has been released. 
Please check app updates.
